# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\pub\Downloads\opencv\design.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(729, 457)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.effect_1 = QtWidgets.QLabel(self.centralWidget)
        self.effect_1.setObjectName("effect_1")
        self.gridLayout.addWidget(self.effect_1, 1, 1, 1, 2)
        self.date_1 = QtWidgets.QLabel(self.centralWidget)
        self.date_1.setObjectName("date_1")
        self.gridLayout.addWidget(self.date_1, 1, 0, 1, 1)
        self.pushButton_n5 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_n5.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_n5.setObjectName("pushButton_n5")
        self.gridLayout.addWidget(self.pushButton_n5, 9, 6, 1, 1)
        self.pushButton_n6 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_n6.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_n6.setObjectName("pushButton_n6")
        self.gridLayout.addWidget(self.pushButton_n6, 10, 6, 1, 1)
        self.radioButton_5 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_5.setObjectName("radioButton_5")
        self.buttonGroup_3 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_3.setObjectName("buttonGroup_3")
        self.buttonGroup_3.addButton(self.radioButton_5)
        self.gridLayout.addWidget(self.radioButton_5, 12, 1, 1, 1)
        self.pushButton_n2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_n2.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_n2.setObjectName("pushButton_n2")
        self.gridLayout.addWidget(self.pushButton_n2, 3, 6, 1, 1)
        self.date_3 = QtWidgets.QLabel(self.centralWidget)
        self.date_3.setObjectName("date_3")
        self.gridLayout.addWidget(self.date_3, 1, 3, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName("radioButton_4")
        self.buttonGroup_3.addButton(self.radioButton_4)
        self.gridLayout.addWidget(self.radioButton_4, 12, 0, 1, 1)
        self.radioButton_1 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_1.setChecked(True)
        self.radioButton_1.setObjectName("radioButton_1")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_1)
        self.gridLayout.addWidget(self.radioButton_1, 7, 0, 1, 1)
        self.radioButton_11 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_11.setObjectName("radioButton_11")
        self.buttonGroup_4 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_4.setObjectName("buttonGroup_4")
        self.buttonGroup_4.addButton(self.radioButton_11)
        self.gridLayout.addWidget(self.radioButton_11, 12, 4, 1, 1)
        self.radioButton_10 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_10.setChecked(True)
        self.radioButton_10.setObjectName("radioButton_10")
        self.buttonGroup_4.addButton(self.radioButton_10)
        self.gridLayout.addWidget(self.radioButton_10, 12, 3, 1, 1)
        self.pushButton_n7 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_n7.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_n7.setObjectName("pushButton_n7")
        self.gridLayout.addWidget(self.pushButton_n7, 11, 6, 2, 1)
        self.pushButton_n1 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_n1.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_n1.setObjectName("pushButton_n1")
        self.gridLayout.addWidget(self.pushButton_n1, 1, 6, 2, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_2.setAutoExclusive(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.gridLayout.addWidget(self.radioButton_2, 7, 1, 1, 1)
        self.radioButton_7 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_7.setCheckable(True)
        self.radioButton_7.setChecked(True)
        self.radioButton_7.setAutoExclusive(True)
        self.radioButton_7.setObjectName("radioButton_7")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radioButton_7)
        self.gridLayout.addWidget(self.radioButton_7, 7, 3, 1, 1)
        self.pushButton_n4 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_n4.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_n4.setObjectName("pushButton_n4")
        self.gridLayout.addWidget(self.pushButton_n4, 7, 6, 2, 1)
        self.date_4 = QtWidgets.QLabel(self.centralWidget)
        self.date_4.setObjectName("date_4")
        self.gridLayout.addWidget(self.date_4, 8, 3, 1, 1)
        self.date_2 = QtWidgets.QLabel(self.centralWidget)
        self.date_2.setObjectName("date_2")
        self.gridLayout.addWidget(self.date_2, 8, 0, 1, 1)
        self.radioButton_8 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_8.setChecked(False)
        self.radioButton_8.setAutoExclusive(True)
        self.radioButton_8.setObjectName("radioButton_8")
        self.buttonGroup_2.addButton(self.radioButton_8)
        self.gridLayout.addWidget(self.radioButton_8, 7, 4, 1, 1)
        self.radioButton_9 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_9.setObjectName("radioButton_9")
        self.buttonGroup_2.addButton(self.radioButton_9)
        self.gridLayout.addWidget(self.radioButton_9, 7, 5, 1, 1)
        self.effect_3 = QtWidgets.QLabel(self.centralWidget)
        self.effect_3.setObjectName("effect_3")
        self.gridLayout.addWidget(self.effect_3, 1, 4, 1, 2)
        self.radioButton_6 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_6.setObjectName("radioButton_6")
        self.buttonGroup_3.addButton(self.radioButton_6)
        self.gridLayout.addWidget(self.radioButton_6, 12, 2, 1, 1)
        self.radioButton_12 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_12.setObjectName("radioButton_12")
        self.buttonGroup_4.addButton(self.radioButton_12)
        self.gridLayout.addWidget(self.radioButton_12, 12, 5, 1, 1)
        self.video_2 = QtWidgets.QLabel(self.centralWidget)
        self.video_2.setText("")
        self.video_2.setObjectName("video_2")
        self.gridLayout.addWidget(self.video_2, 9, 0, 3, 3)
        self.effect_2 = QtWidgets.QLabel(self.centralWidget)
        self.effect_2.setObjectName("effect_2")
        self.gridLayout.addWidget(self.effect_2, 8, 1, 1, 2)
        self.video_4 = QtWidgets.QLabel(self.centralWidget)
        self.video_4.setText("")
        self.video_4.setObjectName("video_4")
        self.gridLayout.addWidget(self.video_4, 9, 3, 3, 3)
        self.effect_4 = QtWidgets.QLabel(self.centralWidget)
        self.effect_4.setObjectName("effect_4")
        self.gridLayout.addWidget(self.effect_4, 8, 4, 1, 2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup.addButton(self.radioButton_3)
        self.gridLayout.addWidget(self.radioButton_3, 7, 2, 1, 1)
        self.pushButton_n3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_n3.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_n3.setObjectName("pushButton_n3")
        self.gridLayout.addWidget(self.pushButton_n3, 4, 6, 2, 1)
        self.video_3 = QtWidgets.QLabel(self.centralWidget)
        self.video_3.setText("")
        self.video_3.setObjectName("video_3")
        self.gridLayout.addWidget(self.video_3, 2, 3, 4, 3)
        self.video_1 = QtWidgets.QLabel(self.centralWidget)
        self.video_1.setText("")
        self.video_1.setObjectName("video_1")
        self.gridLayout.addWidget(self.video_1, 2, 0, 4, 3)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculon"))
        self.effect_1.setText(_translate("MainWindow", "Эффект"))
        self.date_1.setText(_translate("MainWindow", "Дата"))
        self.pushButton_n5.setText(_translate("MainWindow", "вкл"))
        self.pushButton_n5.setShortcut(_translate("MainWindow", "9"))
        self.pushButton_n6.setText(_translate("MainWindow", "вкл"))
        self.pushButton_n6.setShortcut(_translate("MainWindow", "*"))
        self.radioButton_5.setText(_translate("MainWindow", "Распознование людей"))
        self.pushButton_n2.setText(_translate("MainWindow", "вкл"))
        self.pushButton_n2.setShortcut(_translate("MainWindow", "M"))
        self.date_3.setText(_translate("MainWindow", "Дата"))
        self.radioButton_4.setText(_translate("MainWindow", "Обычный режим"))
        self.radioButton_1.setText(_translate("MainWindow", "Обычный режим"))
        self.radioButton_11.setText(_translate("MainWindow", "Распознавание людей"))
        self.radioButton_10.setText(_translate("MainWindow", "Обычный режим"))
        self.pushButton_n7.setText(_translate("MainWindow", "Потерять охраника"))
        self.pushButton_n1.setText(_translate("MainWindow", "вкл"))
        self.pushButton_n1.setShortcut(_translate("MainWindow", "3"))
        self.radioButton_2.setText(_translate("MainWindow", "Распознование людей"))
        self.radioButton_7.setText(_translate("MainWindow", "Обычный режим"))
        self.pushButton_n4.setText(_translate("MainWindow", "Найти охраника"))
        self.date_4.setText(_translate("MainWindow", "Дата"))
        self.date_2.setText(_translate("MainWindow", "Дата"))
        self.radioButton_8.setText(_translate("MainWindow", "Распознование людей"))
        self.radioButton_9.setText(_translate("MainWindow", "Распознование движений"))
        self.effect_3.setText(_translate("MainWindow", "Эффект"))
        self.radioButton_6.setText(_translate("MainWindow", "Распознование движений"))
        self.radioButton_12.setText(_translate("MainWindow", "Распознование движений"))
        self.effect_2.setText(_translate("MainWindow", "Эффект"))
        self.effect_4.setText(_translate("MainWindow", "Эффекты"))
        self.radioButton_3.setText(_translate("MainWindow", "Распознование движений"))
        self.pushButton_n3.setText(_translate("MainWindow", "вкл"))
        self.pushButton_n3.setShortcut(_translate("MainWindow", "8"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionReset.setShortcut(_translate("MainWindow", "Ctrl+R"))

