# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1002, 671)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(":root {\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"#centralwidget {\n"
"    border-image: url(:/everything/resources/bk.jpg) 0 0 0 0 stretch stretch;\n"
"    background: red;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_bar.sizePolicy().hasHeightForWidth())
        self.top_bar.setSizePolicy(sizePolicy)
        self.top_bar.setMinimumSize(QtCore.QSize(0, 66))
        self.top_bar.setStyleSheet("background: #F0F8FD;\n"
"")
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo = QtWidgets.QWidget(self.top_bar)
        self.logo.setMinimumSize(QtCore.QSize(152, 0))
        self.logo.setMaximumSize(QtCore.QSize(152, 52))
        self.logo.setStyleSheet("background-image: url(:/everything/resources/logo.png);")
        self.logo.setObjectName("logo")
        self.horizontalLayout.addWidget(self.logo)
        self.cameras_btn = QtWidgets.QPushButton(self.top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameras_btn.sizePolicy().hasHeightForWidth())
        self.cameras_btn.setSizePolicy(sizePolicy)
        self.cameras_btn.setStyleSheet("background-image: url(:/everything/resources/buttonBK.jpg);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.cameras_btn.setObjectName("cameras_btn")
        self.horizontalLayout.addWidget(self.cameras_btn)
        self.refresh_btn = QtWidgets.QPushButton(self.top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refresh_btn.sizePolicy().hasHeightForWidth())
        self.refresh_btn.setSizePolicy(sizePolicy)
        self.refresh_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.refresh_btn.setStyleSheet("background-image: url(:/everything/resources/buttonBK.jpg);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.refresh_btn.setObjectName("refresh_btn")
        self.horizontalLayout.addWidget(self.refresh_btn)
        self.settings_btn = QtWidgets.QPushButton(self.top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_btn.sizePolicy().hasHeightForWidth())
        self.settings_btn.setSizePolicy(sizePolicy)
        self.settings_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.settings_btn.setBaseSize(QtCore.QSize(0, 0))
        self.settings_btn.setStyleSheet("background-image: url(:/everything/resources/buttonBK.jpg);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.settings_btn.setObjectName("settings_btn")
        self.horizontalLayout.addWidget(self.settings_btn)
        self.log_btn = QtWidgets.QPushButton(self.top_bar)
        self.log_btn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_btn.sizePolicy().hasHeightForWidth())
        self.log_btn.setSizePolicy(sizePolicy)
        self.log_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.log_btn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.log_btn.setAcceptDrops(False)
        self.log_btn.setToolTipDuration(-1)
        self.log_btn.setStyleSheet("background-image: url(:/everything/resources/buttonBK.jpg);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.log_btn.setAutoDefault(False)
        self.log_btn.setObjectName("log_btn")
        self.horizontalLayout.addWidget(self.log_btn)
        self.exit_btn = QtWidgets.QPushButton(self.top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_btn.sizePolicy().hasHeightForWidth())
        self.exit_btn.setSizePolicy(sizePolicy)
        self.exit_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.exit_btn.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-image: url(:/everything/resources/buttonBK.jpg);")
        self.exit_btn.setObjectName("exit_btn")
        self.horizontalLayout.addWidget(self.exit_btn)
        self.verticalLayout.addWidget(self.top_bar)
        self.stacked_widget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stacked_widget.sizePolicy().hasHeightForWidth())
        self.stacked_widget.setSizePolicy(sizePolicy)
        self.stacked_widget.setObjectName("stacked_widget")
        self.cameras_page = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameras_page.sizePolicy().hasHeightForWidth())
        self.cameras_page.setSizePolicy(sizePolicy)
        self.cameras_page.setObjectName("cameras_page")
        self.cameras_layout = QtWidgets.QGridLayout(self.cameras_page)
        self.cameras_layout.setObjectName("cameras_layout")
        self.stacked_widget.addWidget(self.cameras_page)
        self.settings_page = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_page.sizePolicy().hasHeightForWidth())
        self.settings_page.setSizePolicy(sizePolicy)
        self.settings_page.setObjectName("settings_page")
        self.settings_layout = QtWidgets.QGridLayout(self.settings_page)
        self.settings_layout.setObjectName("settings_layout")
        self.camera_preview_label_container = QtWidgets.QWidget(self.settings_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_preview_label_container.sizePolicy().hasHeightForWidth())
        self.camera_preview_label_container.setSizePolicy(sizePolicy)
        self.camera_preview_label_container.setStyleSheet("background: white;")
        self.camera_preview_label_container.setObjectName("camera_preview_label_container")
        self.settings_layout.addWidget(self.camera_preview_label_container, 0, 1, 1, 1)
        self.module_settings_panel = QtWidgets.QStackedWidget(self.settings_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.module_settings_panel.sizePolicy().hasHeightForWidth())
        self.module_settings_panel.setSizePolicy(sizePolicy)
        self.module_settings_panel.setMinimumSize(QtCore.QSize(0, 200))
        self.module_settings_panel.setMaximumSize(QtCore.QSize(16777215, 200))
        self.module_settings_panel.setStyleSheet("background: white;")
        self.module_settings_panel.setObjectName("module_settings_panel")
        self.detect_objects_module_settings = QtWidgets.QWidget()
        self.detect_objects_module_settings.setObjectName("detect_objects_module_settings")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.detect_objects_module_settings)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.detect_objects_module_settings)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 1, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.detect_objects_module_settings)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_2.addWidget(self.checkBox_2, 2, 0, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.detect_objects_module_settings)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_2.addWidget(self.checkBox_7, 3, 1, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.detect_objects_module_settings)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_2.addWidget(self.checkBox_3, 3, 0, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.detect_objects_module_settings)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_2.addWidget(self.checkBox_6, 2, 1, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.detect_objects_module_settings)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_2.addWidget(self.checkBox_5, 1, 1, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.detect_objects_module_settings)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_2.addWidget(self.checkBox_4, 4, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_11 = QtWidgets.QLabel(self.detect_objects_module_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        self.horizontalSlider = QtWidgets.QSlider(self.detect_objects_module_settings)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_3.addWidget(self.horizontalSlider)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 1, 2, 4, 1)
        self.label_10 = QtWidgets.QLabel(self.detect_objects_module_settings)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 3)
        self.module_settings_panel.addWidget(self.detect_objects_module_settings)
        self.settings_layout.addWidget(self.module_settings_panel, 1, 1, 1, 1)
        self.cameras_panel = QtWidgets.QFrame(self.settings_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameras_panel.sizePolicy().hasHeightForWidth())
        self.cameras_panel.setSizePolicy(sizePolicy)
        self.cameras_panel.setMinimumSize(QtCore.QSize(200, 0))
        self.cameras_panel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.cameras_panel.setStyleSheet("background: white;")
        self.cameras_panel.setObjectName("cameras_panel")
        self.cameras_panel_layout = QtWidgets.QVBoxLayout(self.cameras_panel)
        self.cameras_panel_layout.setObjectName("cameras_panel_layout")
        self.label = QtWidgets.QLabel(self.cameras_panel)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.cameras_panel_layout.addWidget(self.label)
        self.cameras_treeview = QtWidgets.QTreeWidget(self.cameras_panel)
        self.cameras_treeview.setObjectName("cameras_treeview")
        self.cameras_treeview.headerItem().setText(0, "1")
        self.cameras_treeview.header().setVisible(False)
        self.cameras_panel_layout.addWidget(self.cameras_treeview)
        self.cameras_panel_buttons_layout = QtWidgets.QHBoxLayout()
        self.cameras_panel_buttons_layout.setObjectName("cameras_panel_buttons_layout")
        self.add_zone_btn = QImageButton(self.cameras_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_zone_btn.sizePolicy().hasHeightForWidth())
        self.add_zone_btn.setSizePolicy(sizePolicy)
        self.add_zone_btn.setMinimumSize(QtCore.QSize(0, 32))
        self.add_zone_btn.setMaximumSize(QtCore.QSize(16777215, 32))
        self.add_zone_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_zone_btn.setAlignment(QtCore.Qt.AlignCenter)
        self.add_zone_btn.setObjectName("add_zone_btn")
        self.cameras_panel_buttons_layout.addWidget(self.add_zone_btn)
        self.add_camera_btn = QImageButton(self.cameras_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_camera_btn.sizePolicy().hasHeightForWidth())
        self.add_camera_btn.setSizePolicy(sizePolicy)
        self.add_camera_btn.setMinimumSize(QtCore.QSize(0, 32))
        self.add_camera_btn.setMaximumSize(QtCore.QSize(16777215, 32))
        self.add_camera_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_camera_btn.setAlignment(QtCore.Qt.AlignCenter)
        self.add_camera_btn.setObjectName("add_camera_btn")
        self.cameras_panel_buttons_layout.addWidget(self.add_camera_btn)
        self.rename_zone_camera_btn = QImageButton(self.cameras_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rename_zone_camera_btn.sizePolicy().hasHeightForWidth())
        self.rename_zone_camera_btn.setSizePolicy(sizePolicy)
        self.rename_zone_camera_btn.setMinimumSize(QtCore.QSize(0, 32))
        self.rename_zone_camera_btn.setMaximumSize(QtCore.QSize(16777215, 32))
        self.rename_zone_camera_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rename_zone_camera_btn.setAlignment(QtCore.Qt.AlignCenter)
        self.rename_zone_camera_btn.setObjectName("rename_zone_camera_btn")
        self.cameras_panel_buttons_layout.addWidget(self.rename_zone_camera_btn)
        self.remove_zone_camera_btn = QImageButton(self.cameras_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_zone_camera_btn.sizePolicy().hasHeightForWidth())
        self.remove_zone_camera_btn.setSizePolicy(sizePolicy)
        self.remove_zone_camera_btn.setMinimumSize(QtCore.QSize(0, 32))
        self.remove_zone_camera_btn.setMaximumSize(QtCore.QSize(16777215, 32))
        self.remove_zone_camera_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.remove_zone_camera_btn.setAlignment(QtCore.Qt.AlignCenter)
        self.remove_zone_camera_btn.setObjectName("remove_zone_camera_btn")
        self.cameras_panel_buttons_layout.addWidget(self.remove_zone_camera_btn)
        self.cameras_panel_layout.addLayout(self.cameras_panel_buttons_layout)
        self.settings_layout.addWidget(self.cameras_panel, 0, 0, 2, 1)
        self.modules_panel = QtWidgets.QFrame(self.settings_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modules_panel.sizePolicy().hasHeightForWidth())
        self.modules_panel.setSizePolicy(sizePolicy)
        self.modules_panel.setMinimumSize(QtCore.QSize(200, 0))
        self.modules_panel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.modules_panel.setStyleSheet("background: white;")
        self.modules_panel.setObjectName("modules_panel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.modules_panel)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.modules_panel)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.camera_access_tb = QtWidgets.QLineEdit(self.modules_panel)
        self.camera_access_tb.setObjectName("camera_access_tb")
        self.verticalLayout_2.addWidget(self.camera_access_tb)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_8 = QtWidgets.QLabel(self.modules_panel)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.modules_panel)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.modules_panel)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.camera_pos_row_spinbox = QtWidgets.QSpinBox(self.modules_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_pos_row_spinbox.sizePolicy().hasHeightForWidth())
        self.camera_pos_row_spinbox.setSizePolicy(sizePolicy)
        self.camera_pos_row_spinbox.setMinimumSize(QtCore.QSize(60, 0))
        self.camera_pos_row_spinbox.setMinimum(1)
        self.camera_pos_row_spinbox.setObjectName("camera_pos_row_spinbox")
        self.gridLayout.addWidget(self.camera_pos_row_spinbox, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.modules_panel)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.modules_panel)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.camera_pos_col_spinbox = QtWidgets.QSpinBox(self.modules_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_pos_col_spinbox.sizePolicy().hasHeightForWidth())
        self.camera_pos_col_spinbox.setSizePolicy(sizePolicy)
        self.camera_pos_col_spinbox.setMinimumSize(QtCore.QSize(60, 0))
        self.camera_pos_col_spinbox.setMinimum(1)
        self.camera_pos_col_spinbox.setObjectName("camera_pos_col_spinbox")
        self.gridLayout.addWidget(self.camera_pos_col_spinbox, 2, 1, 1, 1)
        self.camera_pos_row_span_spinbox = QtWidgets.QSpinBox(self.modules_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_pos_row_span_spinbox.sizePolicy().hasHeightForWidth())
        self.camera_pos_row_span_spinbox.setSizePolicy(sizePolicy)
        self.camera_pos_row_span_spinbox.setMinimumSize(QtCore.QSize(60, 0))
        self.camera_pos_row_span_spinbox.setMinimum(1)
        self.camera_pos_row_span_spinbox.setObjectName("camera_pos_row_span_spinbox")
        self.gridLayout.addWidget(self.camera_pos_row_span_spinbox, 3, 1, 1, 1)
        self.camera_pos_col_span_spinbox = QtWidgets.QSpinBox(self.modules_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_pos_col_span_spinbox.sizePolicy().hasHeightForWidth())
        self.camera_pos_col_span_spinbox.setSizePolicy(sizePolicy)
        self.camera_pos_col_span_spinbox.setMinimumSize(QtCore.QSize(60, 0))
        self.camera_pos_col_span_spinbox.setMinimum(1)
        self.camera_pos_col_span_spinbox.setObjectName("camera_pos_col_span_spinbox")
        self.gridLayout.addWidget(self.camera_pos_col_span_spinbox, 4, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.modules_panel)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.modules_listview = QtWidgets.QListWidget(self.modules_panel)
        self.modules_listview.setObjectName("modules_listview")
        self.verticalLayout_2.addWidget(self.modules_listview)
        self.settings_layout.addWidget(self.modules_panel, 0, 2, 2, 1)
        self.stacked_widget.addWidget(self.settings_page)
        self.verticalLayout.addWidget(self.stacked_widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_6.setBuddy(self.camera_access_tb)
        self.label_4.setBuddy(self.camera_pos_col_spinbox)
        self.label_3.setBuddy(self.camera_pos_row_spinbox)
        self.label_5.setBuddy(self.camera_pos_row_span_spinbox)
        self.label_9.setBuddy(self.camera_pos_col_span_spinbox)

        self.retranslateUi(MainWindow)
        self.stacked_widget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cameras_btn.setText(_translate("MainWindow", "Камеры"))
        self.refresh_btn.setText(_translate("MainWindow", "Обновить"))
        self.settings_btn.setText(_translate("MainWindow", "Настройки"))
        self.log_btn.setText(_translate("MainWindow", "Лог оператора"))
        self.exit_btn.setText(_translate("MainWindow", "Выход"))
        self.checkBox.setText(_translate("MainWindow", "Люди"))
        self.checkBox_2.setText(_translate("MainWindow", "Коты и собаки"))
        self.checkBox_7.setText(_translate("MainWindow", "Грузовики"))
        self.checkBox_3.setText(_translate("MainWindow", "Велосипеды"))
        self.checkBox_6.setText(_translate("MainWindow", "Автобусы"))
        self.checkBox_5.setText(_translate("MainWindow", "Легковые автомобили"))
        self.checkBox_4.setText(_translate("MainWindow", "Мотоциклы"))
        self.label_11.setText(_translate("MainWindow", "Уровень достоверности"))
        self.label_10.setText(_translate("MainWindow", "Описание модуля обнаружения объектов"))
        self.label.setText(_translate("MainWindow", "Список камер"))
        self.add_zone_btn.setToolTip(_translate("MainWindow", "Добавить зону"))
        self.add_zone_btn.setText(_translate("MainWindow", "1"))
        self.add_camera_btn.setToolTip(_translate("MainWindow", "Добавить камеру"))
        self.add_camera_btn.setText(_translate("MainWindow", "2"))
        self.rename_zone_camera_btn.setToolTip(_translate("MainWindow", "Переименовать"))
        self.rename_zone_camera_btn.setText(_translate("MainWindow", "3"))
        self.remove_zone_camera_btn.setToolTip(_translate("MainWindow", "Удалить"))
        self.remove_zone_camera_btn.setText(_translate("MainWindow", "4"))
        self.label_6.setText(_translate("MainWindow", "Доступ к камере"))
        self.label_8.setText(_translate("MainWindow", "Позиция в окне"))
        self.label_4.setText(_translate("MainWindow", "Столбец:"))
        self.label_3.setText(_translate("MainWindow", "Строка:"))
        self.label_5.setText(_translate("MainWindow", "Ширина:"))
        self.label_9.setText(_translate("MainWindow", "Высота:"))
        self.label_2.setText(_translate("MainWindow", "Список модулей"))

from custom_widgets.QImageButton import QImageButton
import xz_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

