# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1002, 671)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(":root {\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"#centralwidget {\n"
"    border-image: url(:/everything/resources/bk.jpg) 0 0 0 0 stretch stretch;\n"
"    background: red;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_bar.sizePolicy().hasHeightForWidth())
        self.top_bar.setSizePolicy(sizePolicy)
        self.top_bar.setMinimumSize(QtCore.QSize(0, 66))
        self.top_bar.setStyleSheet("background: #F0F8FD;\n"
"")
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo = QtWidgets.QWidget(self.top_bar)
        self.logo.setMinimumSize(QtCore.QSize(152, 0))
        self.logo.setMaximumSize(QtCore.QSize(152, 52))
        self.logo.setStyleSheet("background-image: url(:/everything/resources/logo.png);")
        self.logo.setObjectName("logo")
        self.horizontalLayout.addWidget(self.logo)
        self.cameras_btn = QtWidgets.QPushButton(self.top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameras_btn.sizePolicy().hasHeightForWidth())
        self.cameras_btn.setSizePolicy(sizePolicy)
        self.cameras_btn.setStyleSheet("background-image: url(:/everything/resources/buttonBK.jpg);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.cameras_btn.setObjectName("cameras_btn")
        self.horizontalLayout.addWidget(self.cameras_btn)
        self.refresh_btn = QtWidgets.QPushButton(self.top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refresh_btn.sizePolicy().hasHeightForWidth())
        self.refresh_btn.setSizePolicy(sizePolicy)
        self.refresh_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.refresh_btn.setStyleSheet("background-image: url(:/everything/resources/buttonBK.jpg);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.refresh_btn.setObjectName("refresh_btn")
        self.horizontalLayout.addWidget(self.refresh_btn)
        self.settings_btn = QtWidgets.QPushButton(self.top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_btn.sizePolicy().hasHeightForWidth())
        self.settings_btn.setSizePolicy(sizePolicy)
        self.settings_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.settings_btn.setBaseSize(QtCore.QSize(0, 0))
        self.settings_btn.setStyleSheet("background-image: url(:/everything/resources/buttonBK.jpg);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.settings_btn.setObjectName("settings_btn")
        self.horizontalLayout.addWidget(self.settings_btn)
        self.log_btn = QtWidgets.QPushButton(self.top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_btn.sizePolicy().hasHeightForWidth())
        self.log_btn.setSizePolicy(sizePolicy)
        self.log_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.log_btn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.log_btn.setAcceptDrops(False)
        self.log_btn.setToolTipDuration(-1)
        self.log_btn.setStyleSheet("background-image: url(:/everything/resources/buttonBK.jpg);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.log_btn.setAutoDefault(False)
        self.log_btn.setObjectName("log_btn")
        self.horizontalLayout.addWidget(self.log_btn)
        self.exit_btn = QtWidgets.QPushButton(self.top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_btn.sizePolicy().hasHeightForWidth())
        self.exit_btn.setSizePolicy(sizePolicy)
        self.exit_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.exit_btn.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-image: url(:/everything/resources/buttonBK.jpg);")
        self.exit_btn.setObjectName("exit_btn")
        self.horizontalLayout.addWidget(self.exit_btn)
        self.verticalLayout.addWidget(self.top_bar)
        self.stacked_widget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stacked_widget.sizePolicy().hasHeightForWidth())
        self.stacked_widget.setSizePolicy(sizePolicy)
        self.stacked_widget.setObjectName("stacked_widget")
        self.cameras_page = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameras_page.sizePolicy().hasHeightForWidth())
        self.cameras_page.setSizePolicy(sizePolicy)
        self.cameras_page.setObjectName("cameras_page")
        self.cameras_layout = QtWidgets.QGridLayout(self.cameras_page)
        self.cameras_layout.setObjectName("cameras_layout")
        self.stacked_widget.addWidget(self.cameras_page)
        self.settings_page = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_page.sizePolicy().hasHeightForWidth())
        self.settings_page.setSizePolicy(sizePolicy)
        self.settings_page.setObjectName("settings_page")
        self.settings_layout = QtWidgets.QGridLayout(self.settings_page)
        self.settings_layout.setObjectName("settings_layout")
        self.modules_container = QtWidgets.QWidget(self.settings_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modules_container.sizePolicy().hasHeightForWidth())
        self.modules_container.setSizePolicy(sizePolicy)
        self.modules_container.setMinimumSize(QtCore.QSize(200, 0))
        self.modules_container.setMaximumSize(QtCore.QSize(200, 16777215))
        self.modules_container.setStyleSheet("background: white;")
        self.modules_container.setObjectName("modules_container")
        self.settings_layout.addWidget(self.modules_container, 0, 2, 1, 1)
        self.camera_preview_label_container = QtWidgets.QWidget(self.settings_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_preview_label_container.sizePolicy().hasHeightForWidth())
        self.camera_preview_label_container.setSizePolicy(sizePolicy)
        self.camera_preview_label_container.setStyleSheet("background: white;")
        self.camera_preview_label_container.setObjectName("camera_preview_label_container")
        self.settings_layout.addWidget(self.camera_preview_label_container, 0, 1, 1, 1)
        self.module_settings_container = QtWidgets.QWidget(self.settings_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.module_settings_container.sizePolicy().hasHeightForWidth())
        self.module_settings_container.setSizePolicy(sizePolicy)
        self.module_settings_container.setMinimumSize(QtCore.QSize(0, 150))
        self.module_settings_container.setMaximumSize(QtCore.QSize(16777215, 150))
        self.module_settings_container.setStyleSheet("background: white;")
        self.module_settings_container.setObjectName("module_settings_container")
        self.settings_layout.addWidget(self.module_settings_container, 1, 1, 1, 1)
        self.module_description_container = QtWidgets.QWidget(self.settings_page)
        self.module_description_container.setStyleSheet("background: white;")
        self.module_description_container.setObjectName("module_description_container")
        self.settings_layout.addWidget(self.module_description_container, 1, 2, 1, 1)
        self.cameras_treeview = QtWidgets.QTreeView(self.settings_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameras_treeview.sizePolicy().hasHeightForWidth())
        self.cameras_treeview.setSizePolicy(sizePolicy)
        self.cameras_treeview.setMinimumSize(QtCore.QSize(200, 0))
        self.cameras_treeview.setMaximumSize(QtCore.QSize(200, 16777215))
        self.cameras_treeview.setObjectName("cameras_treeview")
        self.settings_layout.addWidget(self.cameras_treeview, 0, 0, 2, 1)
        self.stacked_widget.addWidget(self.settings_page)
        self.verticalLayout.addWidget(self.stacked_widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stacked_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cameras_btn.setText(_translate("MainWindow", "Камеры"))
        self.refresh_btn.setText(_translate("MainWindow", "Обновить"))
        self.settings_btn.setText(_translate("MainWindow", "Настройки"))
        self.log_btn.setText(_translate("MainWindow", "Лог оператора"))
        self.exit_btn.setText(_translate("MainWindow", "Выход"))

import xz_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

