# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1002, 671)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(":root {\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"#centralwidget {\n"
"    border-image: url(:/everything/resources/bk.jpg) 0 0 0 0 stretch stretch;\n"
"    background: red;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_bar.sizePolicy().hasHeightForWidth())
        self.top_bar.setSizePolicy(sizePolicy)
        self.top_bar.setMinimumSize(QtCore.QSize(0, 66))
        self.top_bar.setStyleSheet("background: #F0F8FD;\n"
"")
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo = QtWidgets.QWidget(self.top_bar)
        self.logo.setMinimumSize(QtCore.QSize(152, 0))
        self.logo.setMaximumSize(QtCore.QSize(152, 52))
        self.logo.setStyleSheet("background-image: url(:/everything/resources/logo.png);")
        self.logo.setObjectName("logo")
        self.horizontalLayout.addWidget(self.logo)
        self.cameras_btn = QtWidgets.QPushButton(self.top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameras_btn.sizePolicy().hasHeightForWidth())
        self.cameras_btn.setSizePolicy(sizePolicy)
        self.cameras_btn.setStyleSheet("background-image: url(:/everything/resources/buttonBK.jpg);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.cameras_btn.setObjectName("cameras_btn")
        self.horizontalLayout.addWidget(self.cameras_btn)
        self.refresh_btn = QtWidgets.QPushButton(self.top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refresh_btn.sizePolicy().hasHeightForWidth())
        self.refresh_btn.setSizePolicy(sizePolicy)
        self.refresh_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.refresh_btn.setStyleSheet("background-image: url(:/everything/resources/buttonBK.jpg);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.refresh_btn.setObjectName("refresh_btn")
        self.horizontalLayout.addWidget(self.refresh_btn)
        self.settings_btn = QtWidgets.QPushButton(self.top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_btn.sizePolicy().hasHeightForWidth())
        self.settings_btn.setSizePolicy(sizePolicy)
        self.settings_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.settings_btn.setBaseSize(QtCore.QSize(0, 0))
        self.settings_btn.setStyleSheet("background-image: url(:/everything/resources/buttonBK.jpg);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.settings_btn.setObjectName("settings_btn")
        self.horizontalLayout.addWidget(self.settings_btn)
        self.log_btn = QtWidgets.QPushButton(self.top_bar)
        self.log_btn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_btn.sizePolicy().hasHeightForWidth())
        self.log_btn.setSizePolicy(sizePolicy)
        self.log_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.log_btn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.log_btn.setAcceptDrops(False)
        self.log_btn.setToolTipDuration(-1)
        self.log_btn.setStyleSheet("background-image: url(:/everything/resources/buttonBK.jpg);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.log_btn.setAutoDefault(False)
        self.log_btn.setObjectName("log_btn")
        self.horizontalLayout.addWidget(self.log_btn)
        self.exit_btn = QtWidgets.QPushButton(self.top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_btn.sizePolicy().hasHeightForWidth())
        self.exit_btn.setSizePolicy(sizePolicy)
        self.exit_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.exit_btn.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-image: url(:/everything/resources/buttonBK.jpg);")
        self.exit_btn.setObjectName("exit_btn")
        self.horizontalLayout.addWidget(self.exit_btn)
        self.verticalLayout.addWidget(self.top_bar)
        self.stacked_widget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stacked_widget.sizePolicy().hasHeightForWidth())
        self.stacked_widget.setSizePolicy(sizePolicy)
        self.stacked_widget.setObjectName("stacked_widget")
        self.cameras_page = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameras_page.sizePolicy().hasHeightForWidth())
        self.cameras_page.setSizePolicy(sizePolicy)
        self.cameras_page.setObjectName("cameras_page")
        self.cameras_layout = QtWidgets.QGridLayout(self.cameras_page)
        self.cameras_layout.setObjectName("cameras_layout")
        self.stacked_widget.addWidget(self.cameras_page)
        self.settings_page = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_page.sizePolicy().hasHeightForWidth())
        self.settings_page.setSizePolicy(sizePolicy)
        self.settings_page.setObjectName("settings_page")
        self.settings_layout = QtWidgets.QGridLayout(self.settings_page)
        self.settings_layout.setObjectName("settings_layout")
        self.module_settings_panel = QtWidgets.QStackedWidget(self.settings_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.module_settings_panel.sizePolicy().hasHeightForWidth())
        self.module_settings_panel.setSizePolicy(sizePolicy)
        self.module_settings_panel.setMinimumSize(QtCore.QSize(0, 200))
        self.module_settings_panel.setMaximumSize(QtCore.QSize(16777215, 200))
        self.module_settings_panel.setStyleSheet("background: white;")
        self.module_settings_panel.setObjectName("module_settings_panel")
        self.detect_objects_settings_page = QtWidgets.QWidget()
        self.detect_objects_settings_page.setObjectName("detect_objects_settings_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.detect_objects_settings_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_10 = QtWidgets.QLabel(self.detect_objects_settings_page)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 4)
        self.detect_objects_cars_chb = QtWidgets.QCheckBox(self.detect_objects_settings_page)
        self.detect_objects_cars_chb.setObjectName("detect_objects_cars_chb")
        self.gridLayout_2.addWidget(self.detect_objects_cars_chb, 1, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_11 = QtWidgets.QLabel(self.detect_objects_settings_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        self.detect_objects_confidence_level_slider = QtWidgets.QSlider(self.detect_objects_settings_page)
        self.detect_objects_confidence_level_slider.setMinimum(1)
        self.detect_objects_confidence_level_slider.setMaximum(100)
        self.detect_objects_confidence_level_slider.setOrientation(QtCore.Qt.Horizontal)
        self.detect_objects_confidence_level_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.detect_objects_confidence_level_slider.setObjectName("detect_objects_confidence_level_slider")
        self.verticalLayout_3.addWidget(self.detect_objects_confidence_level_slider)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 1, 3, 4, 1)
        self.detect_objects_motorcycles_chb = QtWidgets.QCheckBox(self.detect_objects_settings_page)
        self.detect_objects_motorcycles_chb.setObjectName("detect_objects_motorcycles_chb")
        self.gridLayout_2.addWidget(self.detect_objects_motorcycles_chb, 4, 0, 1, 1)
        self.detect_objects_trucks_chb = QtWidgets.QCheckBox(self.detect_objects_settings_page)
        self.detect_objects_trucks_chb.setObjectName("detect_objects_trucks_chb")
        self.gridLayout_2.addWidget(self.detect_objects_trucks_chb, 3, 1, 1, 1)
        self.detect_objects_bicycles_chb = QtWidgets.QCheckBox(self.detect_objects_settings_page)
        self.detect_objects_bicycles_chb.setObjectName("detect_objects_bicycles_chb")
        self.gridLayout_2.addWidget(self.detect_objects_bicycles_chb, 3, 0, 1, 1)
        self.detect_objects_buses_chb = QtWidgets.QCheckBox(self.detect_objects_settings_page)
        self.detect_objects_buses_chb.setObjectName("detect_objects_buses_chb")
        self.gridLayout_2.addWidget(self.detect_objects_buses_chb, 2, 1, 1, 1)
        self.detect_objects_people_chb = QtWidgets.QCheckBox(self.detect_objects_settings_page)
        self.detect_objects_people_chb.setObjectName("detect_objects_people_chb")
        self.gridLayout_2.addWidget(self.detect_objects_people_chb, 1, 0, 1, 1)
        self.detect_objects_cats_dogs_chb = QtWidgets.QCheckBox(self.detect_objects_settings_page)
        self.detect_objects_cats_dogs_chb.setObjectName("detect_objects_cats_dogs_chb")
        self.gridLayout_2.addWidget(self.detect_objects_cats_dogs_chb, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 2, 4, 1)
        self.module_settings_panel.addWidget(self.detect_objects_settings_page)
        self.detect_motion_settings_page = QtWidgets.QWidget()
        self.detect_motion_settings_page.setObjectName("detect_motion_settings_page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.detect_motion_settings_page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_17 = QtWidgets.QLabel(self.detect_motion_settings_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_4.addWidget(self.label_17)
        self.detect_motion_confidence_level_slider = QtWidgets.QSlider(self.detect_motion_settings_page)
        self.detect_motion_confidence_level_slider.setMinimum(1)
        self.detect_motion_confidence_level_slider.setMaximum(100)
        self.detect_motion_confidence_level_slider.setOrientation(QtCore.Qt.Horizontal)
        self.detect_motion_confidence_level_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.detect_motion_confidence_level_slider.setObjectName("detect_motion_confidence_level_slider")
        self.verticalLayout_4.addWidget(self.detect_motion_confidence_level_slider)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 1, 5, 4, 1)
        self.label_16 = QtWidgets.QLabel(self.detect_motion_settings_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 4, 0, 1, 1)
        self.detect_motion_blur_y_spinbox = QtWidgets.QSpinBox(self.detect_motion_settings_page)
        self.detect_motion_blur_y_spinbox.setObjectName("detect_motion_blur_y_spinbox")
        self.gridLayout_3.addWidget(self.detect_motion_blur_y_spinbox, 2, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.detect_motion_settings_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 3, 0, 1, 1)
        self.detect_motion_min_area_spinbox = QtWidgets.QSpinBox(self.detect_motion_settings_page)
        self.detect_motion_min_area_spinbox.setObjectName("detect_motion_min_area_spinbox")
        self.gridLayout_3.addWidget(self.detect_motion_min_area_spinbox, 4, 1, 1, 3)
        self.label_12 = QtWidgets.QLabel(self.detect_motion_settings_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.detect_motion_settings_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.detect_motion_settings_page)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 6)
        self.detect_motion_frame_delay_spinbox = QtWidgets.QSpinBox(self.detect_motion_settings_page)
        self.detect_motion_frame_delay_spinbox.setMinimum(1)
        self.detect_motion_frame_delay_spinbox.setObjectName("detect_motion_frame_delay_spinbox")
        self.gridLayout_3.addWidget(self.detect_motion_frame_delay_spinbox, 1, 1, 1, 3)
        self.detect_motion_blur_x_spinbox = QtWidgets.QSpinBox(self.detect_motion_settings_page)
        self.detect_motion_blur_x_spinbox.setObjectName("detect_motion_blur_x_spinbox")
        self.gridLayout_3.addWidget(self.detect_motion_blur_x_spinbox, 2, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.detect_motion_settings_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 2, 2, 1, 1)
        self.detect_motion_dilate_spinbox = QtWidgets.QSpinBox(self.detect_motion_settings_page)
        self.detect_motion_dilate_spinbox.setObjectName("detect_motion_dilate_spinbox")
        self.gridLayout_3.addWidget(self.detect_motion_dilate_spinbox, 3, 1, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 4, 4, 1)
        self.module_settings_panel.addWidget(self.detect_motion_settings_page)
        self.recognize_faces_settings_page = QtWidgets.QWidget()
        self.recognize_faces_settings_page.setObjectName("recognize_faces_settings_page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.recognize_faces_settings_page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_19 = QtWidgets.QLabel(self.recognize_faces_settings_page)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_5.addWidget(self.label_19)
        self.recognize_faces_confidence_level_slider = QtWidgets.QSlider(self.recognize_faces_settings_page)
        self.recognize_faces_confidence_level_slider.setMinimum(1)
        self.recognize_faces_confidence_level_slider.setMaximum(100)
        self.recognize_faces_confidence_level_slider.setOrientation(QtCore.Qt.Horizontal)
        self.recognize_faces_confidence_level_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.recognize_faces_confidence_level_slider.setObjectName("recognize_faces_confidence_level_slider")
        self.verticalLayout_5.addWidget(self.recognize_faces_confidence_level_slider)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 1, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.recognize_faces_settings_page)
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 0, 0, 1, 1)
        self.module_settings_panel.addWidget(self.recognize_faces_settings_page)
        self.recognize_license_plates_settings_page = QtWidgets.QWidget()
        self.recognize_license_plates_settings_page.setObjectName("recognize_license_plates_settings_page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.recognize_license_plates_settings_page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_21 = QtWidgets.QLabel(self.recognize_license_plates_settings_page)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 0, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_22 = QtWidgets.QLabel(self.recognize_license_plates_settings_page)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_6.addWidget(self.label_22)
        self.recognize_license_plates_confidence_level_slider = QtWidgets.QSlider(self.recognize_license_plates_settings_page)
        self.recognize_license_plates_confidence_level_slider.setMinimum(1)
        self.recognize_license_plates_confidence_level_slider.setMaximum(100)
        self.recognize_license_plates_confidence_level_slider.setOrientation(QtCore.Qt.Horizontal)
        self.recognize_license_plates_confidence_level_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.recognize_license_plates_confidence_level_slider.setObjectName("recognize_license_plates_confidence_level_slider")
        self.verticalLayout_6.addWidget(self.recognize_license_plates_confidence_level_slider)
        self.gridLayout_5.addLayout(self.verticalLayout_6, 1, 0, 1, 1)
        self.module_settings_panel.addWidget(self.recognize_license_plates_settings_page)
        self.detect_borders_settings_page = QtWidgets.QWidget()
        self.detect_borders_settings_page.setObjectName("detect_borders_settings_page")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.detect_borders_settings_page)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_20 = QtWidgets.QLabel(self.detect_borders_settings_page)
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 0, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.detect_borders_settings_page)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_6.addWidget(self.listWidget, 1, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton = QtWidgets.QPushButton(self.detect_borders_settings_page)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_7.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.detect_borders_settings_page)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_7.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.detect_borders_settings_page)
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_7.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.detect_borders_settings_page)
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_7.addWidget(self.pushButton_4)
        self.gridLayout_6.addLayout(self.verticalLayout_7, 1, 1, 1, 1)
        self.module_settings_panel.addWidget(self.detect_borders_settings_page)
        self.settings_layout.addWidget(self.module_settings_panel, 1, 1, 1, 1)
        self.cameras_panel = QtWidgets.QFrame(self.settings_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameras_panel.sizePolicy().hasHeightForWidth())
        self.cameras_panel.setSizePolicy(sizePolicy)
        self.cameras_panel.setMinimumSize(QtCore.QSize(200, 0))
        self.cameras_panel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.cameras_panel.setStyleSheet("background: white;")
        self.cameras_panel.setObjectName("cameras_panel")
        self.cameras_panel_layout = QtWidgets.QVBoxLayout(self.cameras_panel)
        self.cameras_panel_layout.setObjectName("cameras_panel_layout")
        self.label = QtWidgets.QLabel(self.cameras_panel)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.cameras_panel_layout.addWidget(self.label)
        self.cameras_treeview = QtWidgets.QTreeWidget(self.cameras_panel)
        self.cameras_treeview.setObjectName("cameras_treeview")
        self.cameras_treeview.headerItem().setText(0, "1")
        self.cameras_treeview.header().setVisible(False)
        self.cameras_panel_layout.addWidget(self.cameras_treeview)
        self.cameras_panel_buttons_layout = QtWidgets.QHBoxLayout()
        self.cameras_panel_buttons_layout.setObjectName("cameras_panel_buttons_layout")
        self.add_zone_btn = QImageButton(self.cameras_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_zone_btn.sizePolicy().hasHeightForWidth())
        self.add_zone_btn.setSizePolicy(sizePolicy)
        self.add_zone_btn.setMinimumSize(QtCore.QSize(32, 32))
        self.add_zone_btn.setMaximumSize(QtCore.QSize(16777215, 32))
        self.add_zone_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_zone_btn.setAlignment(QtCore.Qt.AlignCenter)
        self.add_zone_btn.setObjectName("add_zone_btn")
        self.cameras_panel_buttons_layout.addWidget(self.add_zone_btn)
        self.add_camera_btn = QImageButton(self.cameras_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_camera_btn.sizePolicy().hasHeightForWidth())
        self.add_camera_btn.setSizePolicy(sizePolicy)
        self.add_camera_btn.setMinimumSize(QtCore.QSize(32, 32))
        self.add_camera_btn.setMaximumSize(QtCore.QSize(16777215, 32))
        self.add_camera_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_camera_btn.setAlignment(QtCore.Qt.AlignCenter)
        self.add_camera_btn.setObjectName("add_camera_btn")
        self.cameras_panel_buttons_layout.addWidget(self.add_camera_btn)
        self.rename_zone_camera_btn = QImageButton(self.cameras_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rename_zone_camera_btn.sizePolicy().hasHeightForWidth())
        self.rename_zone_camera_btn.setSizePolicy(sizePolicy)
        self.rename_zone_camera_btn.setMinimumSize(QtCore.QSize(32, 32))
        self.rename_zone_camera_btn.setMaximumSize(QtCore.QSize(16777215, 32))
        self.rename_zone_camera_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rename_zone_camera_btn.setAlignment(QtCore.Qt.AlignCenter)
        self.rename_zone_camera_btn.setObjectName("rename_zone_camera_btn")
        self.cameras_panel_buttons_layout.addWidget(self.rename_zone_camera_btn)
        self.remove_zone_camera_btn = QImageButton(self.cameras_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_zone_camera_btn.sizePolicy().hasHeightForWidth())
        self.remove_zone_camera_btn.setSizePolicy(sizePolicy)
        self.remove_zone_camera_btn.setMinimumSize(QtCore.QSize(32, 32))
        self.remove_zone_camera_btn.setMaximumSize(QtCore.QSize(16777215, 32))
        self.remove_zone_camera_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.remove_zone_camera_btn.setAlignment(QtCore.Qt.AlignCenter)
        self.remove_zone_camera_btn.setObjectName("remove_zone_camera_btn")
        self.cameras_panel_buttons_layout.addWidget(self.remove_zone_camera_btn)
        self.cameras_panel_layout.addLayout(self.cameras_panel_buttons_layout)
        self.settings_layout.addWidget(self.cameras_panel, 0, 0, 2, 1)
        self.camera_settings_panel = QtWidgets.QFrame(self.settings_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_settings_panel.sizePolicy().hasHeightForWidth())
        self.camera_settings_panel.setSizePolicy(sizePolicy)
        self.camera_settings_panel.setMinimumSize(QtCore.QSize(200, 0))
        self.camera_settings_panel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.camera_settings_panel.setStyleSheet("background: white;")
        self.camera_settings_panel.setObjectName("camera_settings_panel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.camera_settings_panel)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.camera_settings_panel)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.camera_access_tb = QtWidgets.QLineEdit(self.camera_settings_panel)
        self.camera_access_tb.setObjectName("camera_access_tb")
        self.verticalLayout_2.addWidget(self.camera_access_tb)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.label_8 = QtWidgets.QLabel(self.camera_settings_panel)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.camera_settings_panel)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.camera_settings_panel)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.camera_pos_row_spinbox = QtWidgets.QSpinBox(self.camera_settings_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_pos_row_spinbox.sizePolicy().hasHeightForWidth())
        self.camera_pos_row_spinbox.setSizePolicy(sizePolicy)
        self.camera_pos_row_spinbox.setMinimumSize(QtCore.QSize(60, 0))
        self.camera_pos_row_spinbox.setMinimum(1)
        self.camera_pos_row_spinbox.setObjectName("camera_pos_row_spinbox")
        self.gridLayout.addWidget(self.camera_pos_row_spinbox, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.camera_settings_panel)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.camera_settings_panel)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.camera_pos_col_spinbox = QtWidgets.QSpinBox(self.camera_settings_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_pos_col_spinbox.sizePolicy().hasHeightForWidth())
        self.camera_pos_col_spinbox.setSizePolicy(sizePolicy)
        self.camera_pos_col_spinbox.setMinimumSize(QtCore.QSize(60, 0))
        self.camera_pos_col_spinbox.setMinimum(1)
        self.camera_pos_col_spinbox.setObjectName("camera_pos_col_spinbox")
        self.gridLayout.addWidget(self.camera_pos_col_spinbox, 2, 1, 1, 1)
        self.camera_pos_row_span_spinbox = QtWidgets.QSpinBox(self.camera_settings_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_pos_row_span_spinbox.sizePolicy().hasHeightForWidth())
        self.camera_pos_row_span_spinbox.setSizePolicy(sizePolicy)
        self.camera_pos_row_span_spinbox.setMinimumSize(QtCore.QSize(60, 0))
        self.camera_pos_row_span_spinbox.setMinimum(1)
        self.camera_pos_row_span_spinbox.setObjectName("camera_pos_row_span_spinbox")
        self.gridLayout.addWidget(self.camera_pos_row_span_spinbox, 3, 1, 1, 1)
        self.camera_pos_col_span_spinbox = QtWidgets.QSpinBox(self.camera_settings_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_pos_col_span_spinbox.sizePolicy().hasHeightForWidth())
        self.camera_pos_col_span_spinbox.setSizePolicy(sizePolicy)
        self.camera_pos_col_span_spinbox.setMinimumSize(QtCore.QSize(60, 0))
        self.camera_pos_col_span_spinbox.setMinimum(1)
        self.camera_pos_col_span_spinbox.setObjectName("camera_pos_col_span_spinbox")
        self.gridLayout.addWidget(self.camera_pos_col_span_spinbox, 4, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem3)
        self.label_2 = QtWidgets.QLabel(self.camera_settings_panel)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.modules_listview = QtWidgets.QListWidget(self.camera_settings_panel)
        self.modules_listview.setStyleSheet("")
        self.modules_listview.setWordWrap(True)
        self.modules_listview.setObjectName("modules_listview")
        self.verticalLayout_2.addWidget(self.modules_listview)
        self.settings_layout.addWidget(self.camera_settings_panel, 0, 2, 2, 1)
        self.camera_preview_label_vbox = QtWidgets.QVBoxLayout()
        self.camera_preview_label_vbox.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.camera_preview_label_vbox.setObjectName("camera_preview_label_vbox")
        self.camera_preview_label_hbox = QtWidgets.QHBoxLayout()
        self.camera_preview_label_hbox.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.camera_preview_label_hbox.setObjectName("camera_preview_label_hbox")
        self.camera_preview_label = QtWidgets.QLabel(self.settings_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_preview_label.sizePolicy().hasHeightForWidth())
        self.camera_preview_label.setSizePolicy(sizePolicy)
        self.camera_preview_label.setStyleSheet("background: black;")
        self.camera_preview_label.setText("")
        self.camera_preview_label.setAlignment(QtCore.Qt.AlignCenter)
        self.camera_preview_label.setObjectName("camera_preview_label")
        self.camera_preview_label_hbox.addWidget(self.camera_preview_label)
        self.camera_preview_label_vbox.addLayout(self.camera_preview_label_hbox)
        self.settings_layout.addLayout(self.camera_preview_label_vbox, 0, 1, 1, 1)
        self.stacked_widget.addWidget(self.settings_page)
        self.verticalLayout.addWidget(self.stacked_widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_6.setBuddy(self.camera_access_tb)
        self.label_4.setBuddy(self.camera_pos_col_spinbox)
        self.label_3.setBuddy(self.camera_pos_row_spinbox)
        self.label_5.setBuddy(self.camera_pos_row_span_spinbox)
        self.label_9.setBuddy(self.camera_pos_col_span_spinbox)

        self.retranslateUi(MainWindow)
        self.stacked_widget.setCurrentIndex(0)
        self.module_settings_panel.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cameras_btn.setText(_translate("MainWindow", "Камеры"))
        self.refresh_btn.setText(_translate("MainWindow", "Обновить"))
        self.settings_btn.setText(_translate("MainWindow", "Настройки"))
        self.log_btn.setText(_translate("MainWindow", "Лог оператора"))
        self.exit_btn.setText(_translate("MainWindow", "Выход"))
        self.label_10.setText(_translate("MainWindow", "Описание модуля обнаружения объектов"))
        self.detect_objects_cars_chb.setText(_translate("MainWindow", "Легковые автомобили"))
        self.label_11.setText(_translate("MainWindow", "Уровень достоверности"))
        self.detect_objects_motorcycles_chb.setText(_translate("MainWindow", "Мотоциклы"))
        self.detect_objects_trucks_chb.setText(_translate("MainWindow", "Грузовики"))
        self.detect_objects_bicycles_chb.setText(_translate("MainWindow", "Велосипеды"))
        self.detect_objects_buses_chb.setText(_translate("MainWindow", "Автобусы"))
        self.detect_objects_people_chb.setText(_translate("MainWindow", "Люди"))
        self.detect_objects_cats_dogs_chb.setText(_translate("MainWindow", "Коты и собаки"))
        self.label_17.setText(_translate("MainWindow", "Порог реагирования"))
        self.label_16.setText(_translate("MainWindow", "Минимальная площадь:"))
        self.label_15.setText(_translate("MainWindow", "Размер деталей:"))
        self.label_12.setText(_translate("MainWindow", "Номер кадра для сравнения:"))
        self.label_13.setText(_translate("MainWindow", "Размытие границ:"))
        self.label_7.setText(_translate("MainWindow", "Описание модуля обнаружения движения"))
        self.label_14.setText(_translate("MainWindow", "x"))
        self.label_19.setText(_translate("MainWindow", "Уровень достоверности"))
        self.label_18.setText(_translate("MainWindow", "Описание модуля распознавания лиц"))
        self.label_21.setText(_translate("MainWindow", "Описание модуля распознавания номерных знаков"))
        self.label_22.setText(_translate("MainWindow", "Уровень достоверности"))
        self.label_20.setText(_translate("MainWindow", "Описание модуля контроля границ"))
        self.pushButton.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_2.setText(_translate("MainWindow", "Переименовать"))
        self.pushButton_3.setText(_translate("MainWindow", "Изменить"))
        self.pushButton_4.setText(_translate("MainWindow", "Удалить"))
        self.label.setText(_translate("MainWindow", "Список камер"))
        self.add_zone_btn.setToolTip(_translate("MainWindow", "Добавить зону"))
        self.add_zone_btn.setText(_translate("MainWindow", "1"))
        self.add_camera_btn.setToolTip(_translate("MainWindow", "Добавить камеру"))
        self.add_camera_btn.setText(_translate("MainWindow", "2"))
        self.rename_zone_camera_btn.setToolTip(_translate("MainWindow", "Переименовать"))
        self.rename_zone_camera_btn.setText(_translate("MainWindow", "3"))
        self.remove_zone_camera_btn.setToolTip(_translate("MainWindow", "Удалить"))
        self.remove_zone_camera_btn.setText(_translate("MainWindow", "4"))
        self.label_6.setText(_translate("MainWindow", "Доступ к камере"))
        self.label_8.setText(_translate("MainWindow", "Позиция в окне"))
        self.label_4.setText(_translate("MainWindow", "Столбец:"))
        self.label_3.setText(_translate("MainWindow", "Строка:"))
        self.label_5.setText(_translate("MainWindow", "Ширина:"))
        self.label_9.setText(_translate("MainWindow", "Высота:"))
        self.label_2.setText(_translate("MainWindow", "Список модулей"))

from custom_widgets.QImageButton import QImageButton
import xz_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

